# Generated by Django 5.2.13 on 2026-05-01 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_file_file_type_alter_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_type',
        ),
    ]
